//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAbonneeClient.AbonneeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persoon", Namespace="http://schemas.datacontract.org/2004/07/AbonneeServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Persoon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FamilienaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoornaamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAdres {
            get {
                return this.EmailAdresField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAdresField, value) != true)) {
                    this.EmailAdresField = value;
                    this.RaisePropertyChanged("EmailAdres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Familienaam {
            get {
                return this.FamilienaamField;
            }
            set {
                if ((object.ReferenceEquals(this.FamilienaamField, value) != true)) {
                    this.FamilienaamField = value;
                    this.RaisePropertyChanged("Familienaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Voornaam {
            get {
                return this.VoornaamField;
            }
            set {
                if ((object.ReferenceEquals(this.VoornaamField, value) != true)) {
                    this.VoornaamField = value;
                    this.RaisePropertyChanged("Voornaam");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vdab.be/abonneeservice", ConfigurationName="AbonneeServiceReference.IAbonneeService")]
    public interface IAbonneeService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://vdab.be/abonneeservice/IAbonneeService/VoegPersoonToe")]
        void VoegPersoonToe(ConsoleAbonneeClient.AbonneeServiceReference.Persoon persoon);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://vdab.be/abonneeservice/IAbonneeService/VoegPersoonToe")]
        System.Threading.Tasks.Task VoegPersoonToeAsync(ConsoleAbonneeClient.AbonneeServiceReference.Persoon persoon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAbonneeServiceChannel : ConsoleAbonneeClient.AbonneeServiceReference.IAbonneeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AbonneeServiceClient : System.ServiceModel.ClientBase<ConsoleAbonneeClient.AbonneeServiceReference.IAbonneeService>, ConsoleAbonneeClient.AbonneeServiceReference.IAbonneeService {
        
        public AbonneeServiceClient() {
        }
        
        public AbonneeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AbonneeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AbonneeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AbonneeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void VoegPersoonToe(ConsoleAbonneeClient.AbonneeServiceReference.Persoon persoon) {
            base.Channel.VoegPersoonToe(persoon);
        }
        
        public System.Threading.Tasks.Task VoegPersoonToeAsync(ConsoleAbonneeClient.AbonneeServiceReference.Persoon persoon) {
            return base.Channel.VoegPersoonToeAsync(persoon);
        }
    }
}
