//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleBierenServiceHost.BierenServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://vdab.be/bierenservice", ConfigurationName="BierenServiceReference.IBierenService")]
    public interface IBierenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vdab.be/bierenservice/IBierenService/GetTotaalAantalBieren", ReplyAction="http://vdab.be/bierenservice/IBierenService/GetTotaalAantalBierenResponse")]
        int GetTotaalAantalBieren();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vdab.be/bierenservice/IBierenService/GetTotaalAantalBieren", ReplyAction="http://vdab.be/bierenservice/IBierenService/GetTotaalAantalBierenResponse")]
        System.Threading.Tasks.Task<int> GetTotaalAantalBierenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vdab.be/bierenservice/IBierenService/GetAantalBierenTussenAlcohol", ReplyAction="http://vdab.be/bierenservice/IBierenService/GetAantalBierenTussenAlcoholResponse")]
        int GetAantalBierenTussenAlcohol(decimal van, decimal tot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vdab.be/bierenservice/IBierenService/GetAantalBierenTussenAlcohol", ReplyAction="http://vdab.be/bierenservice/IBierenService/GetAantalBierenTussenAlcoholResponse")]
        System.Threading.Tasks.Task<int> GetAantalBierenTussenAlcoholAsync(decimal van, decimal tot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vdab.be/bierenservice/IBierenService/GetBierenMetWoord", ReplyAction="http://vdab.be/bierenservice/IBierenService/GetBierenMetWoordResponse")]
        BierenServiceLibrary.Bier[] GetBierenMetWoord(string woord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://vdab.be/bierenservice/IBierenService/GetBierenMetWoord", ReplyAction="http://vdab.be/bierenservice/IBierenService/GetBierenMetWoordResponse")]
        System.Threading.Tasks.Task<BierenServiceLibrary.Bier[]> GetBierenMetWoordAsync(string woord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBierenServiceChannel : ConsoleBierenServiceHost.BierenServiceReference.IBierenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BierenServiceClient : System.ServiceModel.ClientBase<ConsoleBierenServiceHost.BierenServiceReference.IBierenService>, ConsoleBierenServiceHost.BierenServiceReference.IBierenService {
        
        public BierenServiceClient() {
        }
        
        public BierenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BierenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BierenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BierenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetTotaalAantalBieren() {
            return base.Channel.GetTotaalAantalBieren();
        }
        
        public System.Threading.Tasks.Task<int> GetTotaalAantalBierenAsync() {
            return base.Channel.GetTotaalAantalBierenAsync();
        }
        
        public int GetAantalBierenTussenAlcohol(decimal van, decimal tot) {
            return base.Channel.GetAantalBierenTussenAlcohol(van, tot);
        }
        
        public System.Threading.Tasks.Task<int> GetAantalBierenTussenAlcoholAsync(decimal van, decimal tot) {
            return base.Channel.GetAantalBierenTussenAlcoholAsync(van, tot);
        }
        
        public BierenServiceLibrary.Bier[] GetBierenMetWoord(string woord) {
            return base.Channel.GetBierenMetWoord(woord);
        }
        
        public System.Threading.Tasks.Task<BierenServiceLibrary.Bier[]> GetBierenMetWoordAsync(string woord) {
            return base.Channel.GetBierenMetWoordAsync(woord);
        }
    }
}
